package com.app.interfaces;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;

import javax.swing.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.app.datatypes.DtPasajero;

public class AgregarPasajero extends JFrame {

    private int contador;
    private int cantidad;
    private List<DtPasajero> listPasajes = new ArrayList<>();

    private JPanel panelPasajes;
    private JTextField nombrePasajero;
    private JTextField apellidoPasajero;
    private JButton confirmarPasajeButton;

    public List<DtPasajero> getPasajes() {
        return listPasajes;
    }

    public AgregarPasajero(int n) {
        cantidad = n;
        contador = 0;

        setTitle("Cargando datos..");
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(275, 300);
        setLocationRelativeTo(null);
        setVisible(true);
        add(panelPasajes);

        confirmarPasajeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String nombre = nombrePasajero.getText().trim();
                String apellido = apellidoPasajero.getText().trim();

                if (nombre.isEmpty() || apellido.isEmpty()) {
                    new VentanaMensaje("No puedes dejar campos vacíos..");
                    return;
                }

                // Crear el objeto pasaje (podés usar tu DtPasaje o Pasaje)
                DtPasajero p = new DtPasajero(nombre, apellido);
                if (listPasajes.contains(p)) {
                    new VentanaMensaje("No puedes crear 2 pasajes iguales");
                    dispose();
                    return;
                }
                listPasajes.add(p);
                contador++;

                if (contador == cantidad) {
                    dispose();
                } else {
                    nombrePasajero.setText("");
                    apellidoPasajero.setText("");
                    new VentanaMensaje("Pasaje creado con éxito");
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPasajes = new JPanel();
        panelPasajes.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(50, 20, 50, 20);
        panelPasajes.add(panel1, gbc);
        nombrePasajero = new JTextField();
        nombrePasajero.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(nombrePasajero, gbc);
        apellidoPasajero = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(apellidoPasajero, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Nombre");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Apellido");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label2, gbc);
        confirmarPasajeButton = new JButton();
        confirmarPasajeButton.setText("Confirmar Pasaje");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(20, 0, 0, 0);
        panel1.add(confirmarPasajeButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPasajes;
    }

}
