package com.app.interfaces;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.nio.file.Files;
import java.nio.file.Path;

import javax.swing.*;

import com.app.datatypes.DtVuelo;
import com.app.datatypes.DtReserva;

import com.app.enums.TipoImagen;

import com.app.utils.AuxiliarFunctions;

public class InfoVuelo extends JFrame {

    private AuxiliarFunctions a;

    private JPanel dataVueloPanel;
    private JButton consultarReservasButton;
    private JLabel nombreVuelo;
    private JLabel fechaDespegue;
    private JLabel flyDuration;
    private JLabel cantMaxTuristas;
    private JLabel cantMaxEjecutivos;
    private JLabel fechaAlta;
    private JLabel cantReservas;
    private JLabel capacidadRestante;
    private JPanel dataVueloDisplay;
    private JComboBox jComboBoxReservas;
    private JPanel imagenVueloPanel;
    private ImageIcon imagen;

    public InfoVuelo(DtVuelo dataVuelo, AuxiliarFunctions auxiliar) {
        setContentPane(dataVueloPanel);
        setTitle("Datos del Vuelo: " + dataVuelo.getNombre());
        setResizable(false);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);

        a = auxiliar;
        int cantidadReservas = dataVuelo.getCantReservas();
        int capacidadMaxima = dataVuelo.getMaxEjecutivos() + dataVuelo.getMaxTuristas();

        nombreVuelo.setText(dataVuelo.getNombre());
        fechaDespegue.setText(dataVuelo.getFecha().toString());
        flyDuration.setText(dataVuelo.getDuracion().toString());
        cantMaxTuristas.setText(Integer.toString(dataVuelo.getMaxTuristas()));
        cantMaxEjecutivos.setText(Integer.toString(dataVuelo.getMaxEjecutivos()));
        fechaAlta.setText(dataVuelo.getFechaAlta().toString());
        cantReservas.setText(Integer.toString(cantidadReservas));
        capacidadRestante.setText(Integer.toString(capacidadMaxima - cantidadReservas));

        jComboBoxReservas.setModel(a.getComboReservaVueloModel());

        //new VentanaMensaje(dataVuelo.getUrlImage());

        try {
            Path userImg = AuxiliarFunctions.getImagePath(dataVuelo.getUrlImage(), TipoImagen.VUELO);
            if (!Files.exists(userImg)) {
                throw new IllegalArgumentException("No se encontró la imagen");
            }
            imagen = new ImageIcon(userImg.toAbsolutePath().toString());
        } catch (IllegalArgumentException e) {
            imagen = new ImageIcon(getClass().getResource("/pictures/vuelos/default.jpg"));
        }

        AuxiliarFunctions.mostrarFoto(imagenVueloPanel, imagen, 175, 175, TipoImagen.VUELO);
        a.cargarDatosReservaVueloComboBox(dataVuelo.getNombre());

        pack();
        setLocationRelativeTo(null);
        setVisible(true);

        consultarReservasButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jComboBoxReservas.getSelectedItem() == null || jComboBoxReservas.getSelectedItem().toString().equals("N/A")) {
                    new VentanaMensaje("Seleccione una reserva.");
                    return;
                }

                try {
                    DtReserva reserva = (DtReserva) jComboBoxReservas.getSelectedItem();
                    InfoReserva ventanaReserva = new InfoReserva(reserva, a);
                    setEnabled(false);

                    ventanaReserva.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosed(WindowEvent e) {
                            setEnabled(true);
                        }
                    });
                } catch (IllegalArgumentException ex) {
                    new VentanaMensaje(ex.getMessage());
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        dataVueloPanel = new JPanel();
        dataVueloPanel.setLayout(new GridBagLayout());
        dataVueloDisplay = new JPanel();
        dataVueloDisplay.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(50, 20, 50, 20);
        dataVueloPanel.add(dataVueloDisplay, gbc);
        fechaDespegue = new JLabel();
        fechaDespegue.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(fechaDespegue, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Fecha Despegue:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(label1, gbc);
        nombreVuelo = new JLabel();
        nombreVuelo.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(nombreVuelo, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Nombre: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(label2, gbc);
        flyDuration = new JLabel();
        flyDuration.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(flyDuration, gbc);
        cantMaxTuristas = new JLabel();
        cantMaxTuristas.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(cantMaxTuristas, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Duración:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Cant. Max. Turistas:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(label4, gbc);
        cantMaxEjecutivos = new JLabel();
        cantMaxEjecutivos.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(cantMaxEjecutivos, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Cant. Max. Ejecutivos:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(label5, gbc);
        fechaAlta = new JLabel();
        fechaAlta.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(fechaAlta, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Fecha de Alta:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(label6, gbc);
        cantReservas = new JLabel();
        cantReservas.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(cantReservas, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Cant. Reservas:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(label7, gbc);
        capacidadRestante = new JLabel();
        capacidadRestante.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(capacidadRestante, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Capacidad Restante:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(label8, gbc);
        consultarReservasButton = new JButton();
        consultarReservasButton.setText("\uD83D\uDD0D");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 9;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        dataVueloDisplay.add(consultarReservasButton, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Seleccionar Reserva:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        dataVueloDisplay.add(label9, gbc);
        jComboBoxReservas = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        dataVueloDisplay.add(jComboBoxReservas, gbc);
        imagenVueloPanel = new JPanel();
        imagenVueloPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        dataVueloDisplay.add(imagenVueloPanel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return dataVueloPanel;
    }

}


