package com.app.interfaces;

import com.app.datatypes.DtReserva;
import com.app.utils.AuxiliarFunctions;

import javax.swing.*;
import java.awt.*;

public class InfoReserva extends JFrame {

    private AuxiliarFunctions a;

    private JPanel dataReservaPanel;
    private JPanel dataReservaDisplay;
    private JComboBox jComboBoxPasajeros;
    private JLabel clienteLabel;
    private JLabel fechaLabel;
    private JLabel asientosLabel;
    private JLabel tipoAsientoLabel;
    private JLabel equipajeLabel;
    private JLabel costoLabel;

    public InfoReserva(DtReserva dataReserva, AuxiliarFunctions auxiliar) {
        setTitle("Reservas del vuelo: " + dataReserva.getVuelo().getNombre());
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(350, 300);
        setLocationRelativeTo(null);
        setVisible(true);
        add(dataReservaPanel);

        this.a = auxiliar;

        clienteLabel.setText(dataReserva.getCliente().getNombre());
        fechaLabel.setText(dataReserva.getFecha().toString());
        asientosLabel.setText(Integer.toString(dataReserva.getCantPasajes()));
        tipoAsientoLabel.setText(dataReserva.getTipoAsiento().toString());
        equipajeLabel.setText(Integer.toString(dataReserva.getEquipajeExtra()));
        costoLabel.setText(Float.toString(dataReserva.getCosto()));

        jComboBoxPasajeros.setModel(a.getComboPasajerosReserva());
        a.cargarPasajeros(dataReserva);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        dataReservaPanel = new JPanel();
        dataReservaPanel.setLayout(new GridBagLayout());
        dataReservaDisplay = new JPanel();
        dataReservaDisplay.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(50, 20, 50, 20);
        dataReservaPanel.add(dataReservaDisplay, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Cliente:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(label1, gbc);
        clienteLabel = new JLabel();
        clienteLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(clienteLabel, gbc);
        fechaLabel = new JLabel();
        fechaLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(fechaLabel, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Fecha:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Asientos Reservados:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(label3, gbc);
        asientosLabel = new JLabel();
        asientosLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(asientosLabel, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Tipo de Asientos:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(label4, gbc);
        tipoAsientoLabel = new JLabel();
        tipoAsientoLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(tipoAsientoLabel, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Pasajeros:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(label5, gbc);
        jComboBoxPasajeros = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        dataReservaDisplay.add(jComboBoxPasajeros, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Equipaje:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(label6, gbc);
        equipajeLabel = new JLabel();
        equipajeLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(equipajeLabel, gbc);
        costoLabel = new JLabel();
        costoLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(costoLabel, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Costo:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataReservaDisplay.add(label7, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return dataReservaPanel;
    }

}
