package com.app.interfaces;

import javax.swing.*;

import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import com.app.datatypes.DtPaquete;
import com.app.datatypes.DtRuta;

import com.app.utils.AuxiliarFunctions;

public class InfoPaquete extends JFrame {
    private AuxiliarFunctions a;

    private JLabel nombre;
    private JLabel descripcion;
    private JLabel validezDias;
    private JLabel descuento;
    private JLabel costo;
    private JLabel cantidadRutas;
    private JComboBox jComboBoxRutasVuelo;
    private JPanel dataPaquetePanel;
    private JButton buttonVerRutaDeVuelo;
    private JPanel dataPaqueteDisplay;

    public InfoPaquete(DtPaquete paquete, AuxiliarFunctions auxiliar) {
        setTitle("Datos del paquete: " + paquete.getNombre());
        setResizable(false);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        setSize(500, 300);
        setLocationRelativeTo(null);
        setVisible(true);
        add(dataPaquetePanel);

        this.a = auxiliar;

        nombre.setText(paquete.getNombre());
        descripcion.setText(paquete.getDescripcion());
        validezDias.setText(Integer.toString(paquete.getValidezDias()));
        descuento.setText(Float.toString(paquete.getDescuento()));
        costo.setText(Float.toString(paquete.getCosto()));
        cantidadRutas.setText(Integer.toString(paquete.getRutaEnPaquete().size()));

        jComboBoxRutasVuelo.setModel(a.getComboRutaPaquete());
        a.cargarRutasPaquete(paquete.getNombre());


        buttonVerRutaDeVuelo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jComboBoxRutasVuelo.getSelectedItem() == null || jComboBoxRutasVuelo.getSelectedItem().toString().equals("N/A")) {
                    new VentanaMensaje("Debe seleccionar una ruta de vuelo para ver su información");
                    return;
                }
                try {
                    DtRuta ruta = (DtRuta) jComboBoxRutasVuelo.getSelectedItem();
                    InfoRutaDeVuelo ventanaRuta = new InfoRutaDeVuelo(ruta, a);
                    setEnabled(false);

                    ventanaRuta.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosing(WindowEvent e) {
                            setEnabled(true);
                        }

                        ;
                    });
                } catch (IllegalArgumentException ex) {
                    new VentanaMensaje(ex.getMessage());
                }

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        dataPaquetePanel = new JPanel();
        dataPaquetePanel.setLayout(new GridBagLayout());
        dataPaqueteDisplay = new JPanel();
        dataPaqueteDisplay.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        dataPaquetePanel.add(dataPaqueteDisplay, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Nombre:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(label1, gbc);
        nombre = new JLabel();
        nombre.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(nombre, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Descripcion");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Cantidad de rutas de vuelo:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(label3, gbc);
        jComboBoxRutasVuelo = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        dataPaqueteDisplay.add(jComboBoxRutasVuelo, gbc);
        descripcion = new JLabel();
        descripcion.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(descripcion, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Validez (dias):");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Descuento:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Costo:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(label6, gbc);
        validezDias = new JLabel();
        validezDias.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(validezDias, gbc);
        descuento = new JLabel();
        descuento.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(descuento, gbc);
        costo = new JLabel();
        costo.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(costo, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Rutas de vuelo:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(label7, gbc);
        cantidadRutas = new JLabel();
        cantidadRutas.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataPaqueteDisplay.add(cantidadRutas, gbc);
        buttonVerRutaDeVuelo = new JButton();
        buttonVerRutaDeVuelo.setText("VER RUTA DE VUELO");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        dataPaqueteDisplay.add(buttonVerRutaDeVuelo, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return dataPaquetePanel;
    }

}
