package com.app.interfaces;

import java.awt.*;
import java.nio.file.Files;
import java.nio.file.Path;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.*;
import javax.swing.border.TitledBorder;

import com.app.datatypes.DtCategoria;
import com.app.datatypes.DtRuta;
import com.app.datatypes.DtVuelo;

import com.app.enums.TipoImagen;

import com.app.utils.AuxiliarFunctions;

public class InfoRutaDeVuelo extends JFrame {
    private AuxiliarFunctions a;

    private JPanel panelGeneralRuta;
    private JLabel nombre;
    private JLabel descripcion;
    private JLabel duracion;
    private JLabel costoTurista;
    private JLabel costoEjecutivo;
    private JLabel costoEquipaje;
    private JLabel fechaAlta;
    private JLabel ciudadOrigen;
    private JLabel ciudadDestino;
    private JPanel dataRutaPanel;
    private JPanel categoriasPanel;
    private JComboBox jComboBoxVuelos;
    private JButton buttonVerVuelo;
    private JPanel imagenRutaPanel;
    private JLabel estado;
    private JLabel descripcionCorta;
    private ImageIcon imagen;

    public InfoRutaDeVuelo(DtRuta ruta, AuxiliarFunctions auxiliar) {
        setContentPane(panelGeneralRuta);
        setTitle("Datos de la ruta: " + ruta.getNombre());
        setResizable(false);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);

        a = auxiliar;

        jComboBoxVuelos.setModel(a.getComboVueloRutaDeVueloModel());
        a.cargarVuelosComboBoxRuta(ruta.getNombre());

        nombre.setText(ruta.getNombre());
        descripcion.setText(ruta.getDescripcion());
        descripcionCorta.setText(ruta.getDescripcionCorta());
        duracion.setText(ruta.getDuracion().toString());
        costoTurista.setText(Float.toString(ruta.getCostoTurista()));
        costoEjecutivo.setText(Float.toString(ruta.getCostoEjecutivo()));
        costoEquipaje.setText(Float.toString(ruta.getEquipajeExtra()));
        fechaAlta.setText(ruta.getFechaAlta().toString());
        ciudadOrigen.setText(ruta.getCiudadOrigen().getNombre());
        ciudadDestino.setText(ruta.getCiudadDestino().getNombre());
        estado.setText(ruta.getEstado().toString());


        categoriasPanel.setLayout(new GridLayout(0, 2, 10, 5));

        try {
            Path userImg = AuxiliarFunctions.getImagePath(ruta.getUrlImagen(), TipoImagen.RUTA);
            if (!Files.exists(userImg)) {
                throw new IllegalArgumentException("No se encontró la imagen");
            }
            imagen = new ImageIcon(userImg.toAbsolutePath().toString());
        } catch (IllegalArgumentException ex) {
            imagen = new ImageIcon(getClass().getResource("/pictures/rutas/default.png"));
        }

        AuxiliarFunctions.mostrarFoto(imagenRutaPanel, imagen, 175, 175, TipoImagen.RUTA);

        if (ruta.getCategorias().isEmpty()) {
            categoriasPanel.add(new JLabel("No hay categorías."));
        } else {
            for (DtCategoria cat : ruta.getCategorias()) {
                JLabel label = new JLabel(cat.getNombre());
                categoriasPanel.add(label);
            }
        }

        pack();
        setLocationRelativeTo(null);
        setVisible(true);

        buttonVerVuelo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jComboBoxVuelos.getSelectedItem() == null || jComboBoxVuelos.getSelectedItem().toString().equals("N/A")) {
                    new VentanaMensaje("Seleccione un vuelo para poder verlo.");
                    return;
                }

                DtVuelo v = (DtVuelo) jComboBoxVuelos.getSelectedItem();
                InfoVuelo ventanaVuelo = new InfoVuelo(v.getDatos(), a);
                setEnabled(false);

                ventanaVuelo.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        setEnabled(true);
                    }
                });
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelGeneralRuta = new JPanel();
        panelGeneralRuta.setLayout(new GridBagLayout());
        dataRutaPanel = new JPanel();
        dataRutaPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panelGeneralRuta.add(dataRutaPanel, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Nombre:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Descripción:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label2, gbc);
        nombre = new JLabel();
        nombre.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(nombre, gbc);
        descripcion = new JLabel();
        descripcion.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(descripcion, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Duracion");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label3, gbc);
        duracion = new JLabel();
        duracion.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(duracion, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Costo ejecutivo:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Costo equipaje extra:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label5, gbc);
        costoTurista = new JLabel();
        costoTurista.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(costoTurista, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Costo turista:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label6, gbc);
        costoEjecutivo = new JLabel();
        costoEjecutivo.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(costoEjecutivo, gbc);
        costoEquipaje = new JLabel();
        costoEquipaje.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(costoEquipaje, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Fecha alta:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label7, gbc);
        fechaAlta = new JLabel();
        fechaAlta.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(fechaAlta, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Categorías:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label8, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Ciudad origen:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label9, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("Ciudad destino:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label10, gbc);
        ciudadOrigen = new JLabel();
        ciudadOrigen.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(ciudadOrigen, gbc);
        ciudadDestino = new JLabel();
        ciudadDestino.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 11;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(ciudadDestino, gbc);
        categoriasPanel = new JPanel();
        categoriasPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        dataRutaPanel.add(categoriasPanel, gbc);
        categoriasPanel.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label11 = new JLabel();
        label11.setText("Vuelos:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label11, gbc);
        jComboBoxVuelos = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 13;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        dataRutaPanel.add(jComboBoxVuelos, gbc);
        imagenRutaPanel = new JPanel();
        imagenRutaPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        dataRutaPanel.add(imagenRutaPanel, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 14;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        dataRutaPanel.add(panel1, gbc);
        buttonVerVuelo = new JButton();
        buttonVerVuelo.setText("Ver Vuelo");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(buttonVerVuelo, gbc);
        final JLabel label12 = new JLabel();
        label12.setText("Estado:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 12;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label12, gbc);
        estado = new JLabel();
        estado.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 12;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(estado, gbc);
        final JLabel label13 = new JLabel();
        label13.setText("Descripción corta:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(label13, gbc);
        descripcionCorta = new JLabel();
        descripcionCorta.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dataRutaPanel.add(descripcionCorta, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelGeneralRuta;
    }

}
