package com.app.interfaces;

import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JFrame;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.io.File;

import com.app.enums.TipoImagen;
import com.app.utils.AuxiliarFunctions;

public class SubirImagen extends JFrame {
    private JButton confirmarButton;
    private JButton cancelarButton;
    private JPanel imagePanel;
    private JPanel panelGlobal;
    private ImageIcon profileImage;
    private File selectedFile;
    private TipoImagen imgType;

    public SubirImagen(TipoImagen tipo) {
        setContentPane(panelGlobal);
        setTitle("Subir imagen");
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        imgType = tipo;

        try {
            if (!abrirFileChooser()) {
                selectedFile = null;
                dispose();
                return;
            }
        } catch (IllegalArgumentException e) {
            selectedFile = null;
            dispose();
            return;
        }

        pack();
        setLocationRelativeTo(null);
        setVisible(true);

        cancelarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                selectedFile = null;
                dispose();
            }
        });

        confirmarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }

    private boolean abrirFileChooser() {
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Imágenes (JPG, JPEG, PNG)", "jpg", "jpeg", "png"
        );
        fileChooser.setFileFilter(filter);
        fileChooser.setMultiSelectionEnabled(false);

        int option = fileChooser.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();

            String name = selectedFile.getName().toLowerCase();
            if (!(name.endsWith(".jpg") || name.endsWith(".jpeg") || name.endsWith(".png"))) {
                new VentanaMensaje("Debes seleccionar un archivo válido (jpg, jpeg o png)");
                return false;
            }

            profileImage = new ImageIcon(selectedFile.getAbsolutePath());
            Image imgRaw = profileImage.getImage();
            Image imgScaled = imgRaw.getScaledInstance(175, 175, Image.SCALE_SMOOTH);
            profileImage = new ImageIcon(imgScaled);

            if (imgType == TipoImagen.USUARIO) {
                profileImage = AuxiliarFunctions.createRoundImageIcon(profileImage);
            }

            JLabel imgLabel = new JLabel(profileImage);

            imagePanel.setLayout(new FlowLayout());
            imagePanel.removeAll();
            imagePanel.add(imgLabel);
            imagePanel.revalidate();
            imagePanel.repaint();

            return true;
        }

        return false;
    }

    public File getImagen() {
        return selectedFile;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panelGlobal = new JPanel();
        panelGlobal.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panelGlobal, gbc);
        imagePanel = new JPanel();
        imagePanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panelGlobal.add(imagePanel, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panelGlobal.add(panel2, gbc);
        cancelarButton = new JButton();
        cancelarButton.setText("Cancelar");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(cancelarButton, gbc);
        confirmarButton = new JButton();
        confirmarButton.setText("Confirmar");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(confirmarButton, gbc);
    }
}